"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Header from "../../components/shared/Header";
import AlertProvider from "components/customAlertModal/AlertProvider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='hide-scrollbar m-0 p-0'>
      <body className="hide-scrollbar">
        <div className="rainbow-bg hide-scrollbar"></div>
        <AlertProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
